# Generated by Django 4.1.4 on 2022-12-31 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('cover', models.FileField(null=True, upload_to='cover/')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('translator', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('press', models.CharField(blank=True, max_length=50, null=True)),
                ('page_count', models.IntegerField(default=0)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateField(null=True)),
                ('online_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('0', '上架'), ('1', '下架')], default='0', max_length=1)),
                ('repertory', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('layout', models.CharField(choices=[('0', '平装'), ('1', '精装'), ('2', '其它')], default='0', max_length=1)),
                ('pv', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'b_book',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'b_classification',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'b_tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('0', '管理员'), ('1', '普通用户')], max_length=1, null=True)),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '封号')], default='0', max_length=1)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.FileField(upload_to='avatar/')),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1, null=True)),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'b_user',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('record_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_record', to='myapp.book')),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='myapp.classification')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_record', to='myapp.user')),
            ],
            options={
                'db_table': 'b_record',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_comment', to='myapp.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='myapp.user')),
            ],
            options={
                'db_table': 'b_comment',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_book', to='myapp.classification'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_book', to='myapp.tag'),
        ),
    ]
