# Generated by Django 4.1.4 on 2022-12-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_password_user_username_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
