# Generated by Django 4.1.4 on 2023-01-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='layout',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
