# Generated by Django 4.1.4 on 2023-01-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_book_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
