# Generated by Django 4.1.4 on 2023-01-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
