# Generated by Django 4.1.4 on 2023-01-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_classification_create_time_tag_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tag_book', to='myapp.tag'),
        ),
    ]
