# Generated by Django 4.1.4 on 2023-01-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_book_classification_alter_book_layout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, to='myapp.tag'),
        ),
    ]
